//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlasterLog
    {
        public int Id { get; set; }
        public int EmailBlasterLogsId { get; set; }
        public int EmailBlasterTemplateId { get; set; }
        public int ReportId { get; set; }
    
        public virtual EmailBlasterLogs EmailBlasterLog { get; set; }
        public virtual EmailBlasterTemplate EmailBlasterTemplate { get; set; }
    }
}
