//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRateUnitPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarRateUnitPackage()
        {
            this.CarResPackages = new HashSet<CarResPackage>();
        }
    
        public int Id { get; set; }
        public int CarRatePackageId { get; set; }
        public int CarUnitId { get; set; }
        public string RentalRate { get; set; }
        public string FuelLonghaul { get; set; }
        public string FuelDaily { get; set; }
    
        public virtual CarRatePackage CarRatePackage { get; set; }
        public virtual CarUnit CarUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarResPackage> CarResPackages { get; set; }
    }
}
