//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRateGroup
    {
        public int Id { get; set; }
        public int RateGroupId { get; set; }
        public int CarRatePackageId { get; set; }
    
        public virtual RateGroup RateGroup { get; set; }
        public virtual CarRatePackage CarRatePackage { get; set; }
    }
}
