//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarResPackage
    {
        public int Id { get; set; }
        public int CarRateUnitPackageId { get; set; }
        public int CarReservationId { get; set; }
        public string DrvMealStatus { get; set; }
        public string DrvRoomStatus { get; set; }
        public string FuelStatus { get; set; }
    
        public virtual CarRateUnitPackage CarRateUnitPackage { get; set; }
        public virtual CarReservation CarReservation { get; set; }
    }
}
